// Diccionario de comercios de México. Capa 1 del categorizador: barato, explicable y editable.
// patron = fragmento normalizado (sin acentos, mayúsculas, sin dígitos) que debe aparecer en la descripción.

export type ComercioConocido = {
  patron: string;
  nombre: string;
  dominio: string;
  categoria: string;
  suscripcion?: boolean;
  /** Servicio del hogar (CFE, agua, internet, celular): recurrente pero no "suscripción" cancelable en línea. */
  servicio?: boolean;
  /** Enlace directo de cancelación (cancelación guiada). */
  cancelarUrl?: string;
  /** Patrón genérico (RESTAURANT, CAFE, SEGURO…): solo aplica si ninguna marca coincide. */
  generico?: boolean;
};

export const COMERCIOS: ComercioConocido[] = [
  // Streaming y suscripciones digitales
  { patron: 'NETFLIX', nombre: 'Netflix', dominio: 'netflix.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.netflix.com/cancelplan' },
  { patron: 'SPOTIFY', nombre: 'Spotify', dominio: 'spotify.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.spotify.com/mx/account/subscription/' },
  { patron: 'DISNEY', nombre: 'Disney+', dominio: 'disneyplus.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.disneyplus.com/account' },
  { patron: 'HBO', nombre: 'HBO Max', dominio: 'max.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://auth.max.com/subscription' },
  { patron: 'MAX.COM', nombre: 'HBO Max', dominio: 'max.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://auth.max.com/subscription' },
  { patron: 'PRIME VIDEO', nombre: 'Prime Video', dominio: 'primevideo.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.amazon.com.mx/gp/primecentral' },
  { patron: 'AMAZON PRIME', nombre: 'Amazon Prime', dominio: 'amazon.com.mx', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.amazon.com.mx/gp/primecentral' },
  { patron: 'AMZN PRIME', nombre: 'Amazon Prime', dominio: 'amazon.com.mx', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.amazon.com.mx/gp/primecentral' },
  { patron: 'YOUTUBE', nombre: 'YouTube Premium', dominio: 'youtube.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.youtube.com/paid_memberships' },
  { patron: 'GOOGLE ONE', nombre: 'Google One', dominio: 'one.google.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://one.google.com/settings' },
  { patron: 'GOOGLE *', nombre: 'Google', dominio: 'google.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://play.google.com/store/account/subscriptions' },
  { patron: 'APPLE.COM/BILL', nombre: 'Apple', dominio: 'apple.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://support.apple.com/es-mx/HT202039' },
  { patron: 'APPLE COM BILL', nombre: 'Apple', dominio: 'apple.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://support.apple.com/es-mx/HT202039' },
  { patron: 'ITUNES', nombre: 'Apple', dominio: 'apple.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://support.apple.com/es-mx/HT202039' },
  { patron: 'ICLOUD', nombre: 'iCloud', dominio: 'icloud.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://support.apple.com/es-mx/HT202039' },
  { patron: 'PARAMOUNT', nombre: 'Paramount+', dominio: 'paramountplus.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.paramountplus.com/account/' },
  { patron: 'CRUNCHYROLL', nombre: 'Crunchyroll', dominio: 'crunchyroll.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.crunchyroll.com/account/membership' },
  { patron: 'VIX', nombre: 'ViX', dominio: 'vix.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://vix.com/es-es/cuenta' },
  { patron: 'XBOX', nombre: 'Xbox', dominio: 'xbox.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://account.microsoft.com/services' },
  { patron: 'MICROSOFT', nombre: 'Microsoft 365', dominio: 'microsoft.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://account.microsoft.com/services' },
  { patron: 'PLAYSTATION', nombre: 'PlayStation', dominio: 'playstation.com', categoria: 'suscripciones', suscripcion: true, cancelarUrl: 'https://www.playstation.com/es-mx/support/subscriptions/' },
  { patron: 'NINTENDO', nombre: 'Nintendo', dominio: 'nintendo.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'CHATGPT', nombre: 'ChatGPT', dominio: 'openai.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'OPENAI', nombre: 'ChatGPT', dominio: 'openai.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'CLAUDE.AI', nombre: 'Claude', dominio: 'claude.ai', categoria: 'suscripciones', suscripcion: true },
  { patron: 'ANTHROPIC', nombre: 'Claude', dominio: 'claude.ai', categoria: 'suscripciones', suscripcion: true },
  { patron: 'DROPBOX', nombre: 'Dropbox', dominio: 'dropbox.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'ADOBE', nombre: 'Adobe', dominio: 'adobe.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'CANVA', nombre: 'Canva', dominio: 'canva.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'DUOLINGO', nombre: 'Duolingo', dominio: 'duolingo.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'TINDER', nombre: 'Tinder', dominio: 'tinder.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'SMART FIT', nombre: 'Smart Fit', dominio: 'smartfit.com.mx', categoria: 'suscripciones', suscripcion: true },
  { patron: 'SMARTFIT', nombre: 'Smart Fit', dominio: 'smartfit.com.mx', categoria: 'suscripciones', suscripcion: true },
  { patron: 'SPORTS WORLD', nombre: 'Sports World', dominio: 'sportsworld.com.mx', categoria: 'suscripciones', suscripcion: true },
  { patron: 'RAPPI PRIME', nombre: 'Rappi Prime', dominio: 'rappi.com.mx', categoria: 'suscripciones', suscripcion: true },
  { patron: 'UBER ONE', nombre: 'Uber One', dominio: 'uber.com', categoria: 'suscripciones', suscripcion: true },
  { patron: 'MERCADO LIBRE MELI+', nombre: 'Meli+', dominio: 'mercadolibre.com.mx', categoria: 'suscripciones', suscripcion: true },
  // Telecom y servicios del hogar
  { patron: 'TELCEL', nombre: 'Telcel', dominio: 'telcel.com', categoria: 'servicios', servicio: true },
  { patron: 'AT&T', nombre: 'AT&T', dominio: 'att.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'ATT MEXICO', nombre: 'AT&T', dominio: 'att.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'MOVISTAR', nombre: 'Movistar', dominio: 'movistar.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'TOTALPLAY', nombre: 'Totalplay', dominio: 'totalplay.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'IZZI', nombre: 'Izzi', dominio: 'izzi.mx', categoria: 'servicios', servicio: true },
  { patron: 'TELMEX', nombre: 'Telmex', dominio: 'telmex.com', categoria: 'servicios', servicio: true },
  { patron: 'MEGACABLE', nombre: 'Megacable', dominio: 'megacable.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'CFE', nombre: 'CFE', dominio: 'cfe.mx', categoria: 'servicios', servicio: true },
  { patron: 'NATURGY', nombre: 'Naturgy', dominio: 'naturgy.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'SACMEX', nombre: 'Agua CDMX', dominio: 'sacmex.cdmx.gob.mx', categoria: 'servicios', servicio: true },
  { patron: 'SKY', nombre: 'Sky', dominio: 'sky.com.mx', categoria: 'servicios', servicio: true },
  { patron: 'DISH', nombre: 'Dish', dominio: 'dish.com.mx', categoria: 'servicios', servicio: true },
  // Súper y conveniencia
  { patron: 'OXXO', nombre: 'Oxxo', dominio: 'oxxo.com', categoria: 'super' },
  { patron: '7 ELEVEN', nombre: '7-Eleven', dominio: '7-eleven.com.mx', categoria: 'super' },
  { patron: '7-ELEVEN', nombre: '7-Eleven', dominio: '7-eleven.com.mx', categoria: 'super' },
  { patron: 'SORIANA', nombre: 'Soriana', dominio: 'soriana.com', categoria: 'super' },
  { patron: 'WALMART', nombre: 'Walmart', dominio: 'walmart.com.mx', categoria: 'super' },
  { patron: 'WAL MART', nombre: 'Walmart', dominio: 'walmart.com.mx', categoria: 'super' },
  { patron: 'BODEGA AURRERA', nombre: 'Bodega Aurrera', dominio: 'bodegaaurrera.com.mx', categoria: 'super' },
  { patron: 'AURRERA', nombre: 'Bodega Aurrera', dominio: 'bodegaaurrera.com.mx', categoria: 'super' },
  { patron: 'CHEDRAUI', nombre: 'Chedraui', dominio: 'chedraui.com.mx', categoria: 'super' },
  { patron: 'LA COMER', nombre: 'La Comer', dominio: 'lacomer.com.mx', categoria: 'super' },
  { patron: 'CITY MARKET', nombre: 'City Market', dominio: 'lacomer.com.mx', categoria: 'super' },
  { patron: 'HEB', nombre: 'HEB', dominio: 'heb.com.mx', categoria: 'super' },
  { patron: 'COSTCO', nombre: 'Costco', dominio: 'costco.com.mx', categoria: 'super' },
  { patron: 'SAMS', nombre: "Sam's Club", dominio: 'sams.com.mx', categoria: 'super' },
  { patron: 'SUPERAMA', nombre: 'Superama', dominio: 'walmart.com.mx', categoria: 'super' },
  { generico: true, patron: 'FARMACIA', nombre: 'Farmacia', dominio: 'farmaciasguadalajara.com', categoria: 'salud' },
  { patron: 'FARMACIAS DEL AHORRO', nombre: 'Farmacias del Ahorro', dominio: 'fahorro.com', categoria: 'salud' },
  { patron: 'SAN PABLO', nombre: 'Farmacia San Pablo', dominio: 'farmaciasanpablo.com.mx', categoria: 'salud' },
  // Comida y entrega
  { patron: 'RAPPI', nombre: 'Rappi', dominio: 'rappi.com.mx', categoria: 'comida' },
  { patron: 'UBER EATS', nombre: 'Uber Eats', dominio: 'ubereats.com', categoria: 'comida' },
  { patron: 'UBER *EATS', nombre: 'Uber Eats', dominio: 'ubereats.com', categoria: 'comida' },
  { patron: 'DIDI FOOD', nombre: 'DiDi Food', dominio: 'didiglobal.com', categoria: 'comida' },
  { patron: 'STARBUCKS', nombre: 'Starbucks', dominio: 'starbucks.com.mx', categoria: 'comida' },
  { patron: 'MCDONALD', nombre: "McDonald's", dominio: 'mcdonalds.com.mx', categoria: 'comida' },
  { patron: 'BURGER KING', nombre: 'Burger King', dominio: 'burgerking.com.mx', categoria: 'comida' },
  { patron: 'DOMINOS', nombre: "Domino's", dominio: 'dominos.com.mx', categoria: 'comida' },
  { patron: 'LITTLE CAESARS', nombre: 'Little Caesars', dominio: 'littlecaesars.com.mx', categoria: 'comida' },
  { patron: 'VIPS', nombre: 'Vips', dominio: 'vips.com.mx', categoria: 'comida' },
  { patron: 'SANBORNS', nombre: 'Sanborns', dominio: 'sanborns.com.mx', categoria: 'comida' },
  { patron: 'TOKS', nombre: 'Toks', dominio: 'toks.com.mx', categoria: 'comida' },
  { patron: 'CARLS JR', nombre: "Carl's Jr.", dominio: 'carlsjr.com.mx', categoria: 'comida' },
  { patron: 'SUBWAY', nombre: 'Subway', dominio: 'subway.com', categoria: 'comida' },
  { patron: 'KFC', nombre: 'KFC', dominio: 'kfc.com.mx', categoria: 'comida' },
  { generico: true, patron: 'RESTAURANT', nombre: 'Restaurante', dominio: '', categoria: 'comida' },
  { generico: true, patron: 'TAQUERIA', nombre: 'Taquería', dominio: '', categoria: 'comida' },
  { generico: true, patron: 'CAFE', nombre: 'Café', dominio: '', categoria: 'comida' },
  // Transporte
  { patron: 'UBER', nombre: 'Uber', dominio: 'uber.com', categoria: 'transporte' },
  { patron: 'DIDI', nombre: 'DiDi', dominio: 'didiglobal.com', categoria: 'transporte' },
  { patron: 'CABIFY', nombre: 'Cabify', dominio: 'cabify.com', categoria: 'transporte' },
  { generico: true, patron: 'GASOLINA', nombre: 'Gasolina', dominio: 'pemex.com', categoria: 'transporte' },
  { patron: 'PEMEX', nombre: 'Gasolina Pemex', dominio: 'pemex.com', categoria: 'transporte' },
  { patron: 'GAS BP', nombre: 'Gasolina BP', dominio: 'bp.com', categoria: 'transporte' },
  { patron: 'BP ', nombre: 'Gasolina BP', dominio: 'bp.com', categoria: 'transporte' },
  { patron: 'SHELL', nombre: 'Gasolina Shell', dominio: 'shell.com.mx', categoria: 'transporte' },
  { patron: 'MOBIL', nombre: 'Gasolina Mobil', dominio: 'mobil.com.mx', categoria: 'transporte' },
  { patron: 'G500', nombre: 'Gasolina G500', dominio: 'g500.com.mx', categoria: 'transporte' },
  { patron: 'OXXO GAS', nombre: 'Oxxo Gas', dominio: 'oxxogas.com', categoria: 'transporte' },
  { generico: true, patron: 'ESTACIONAMIENTO', nombre: 'Estacionamiento', dominio: '', categoria: 'transporte' },
  { generico: true, patron: 'AUTOPISTA', nombre: 'Autopista', dominio: '', categoria: 'transporte' },
  { patron: 'CAPUFE', nombre: 'Caseta Capufe', dominio: 'capufe.gob.mx', categoria: 'transporte' },
  { generico: true, patron: 'TELEPEAJE', nombre: 'Telepeaje', dominio: '', categoria: 'transporte' },
  { generico: true, patron: 'METRO', nombre: 'Metro', dominio: '', categoria: 'transporte' },
  { patron: 'AEROMEXICO', nombre: 'Aeroméxico', dominio: 'aeromexico.com', categoria: 'viajes' },
  { patron: 'VOLARIS', nombre: 'Volaris', dominio: 'volaris.com', categoria: 'viajes' },
  { patron: 'VIVA AEROBUS', nombre: 'Viva Aerobus', dominio: 'vivaaerobus.com', categoria: 'viajes' },
  { patron: 'AIRBNB', nombre: 'Airbnb', dominio: 'airbnb.mx', categoria: 'viajes' },
  { patron: 'BOOKING', nombre: 'Booking', dominio: 'booking.com', categoria: 'viajes' },
  // Compras en línea y retail
  { patron: 'AMAZON', nombre: 'Amazon', dominio: 'amazon.com.mx', categoria: 'online' },
  { patron: 'AMZN', nombre: 'Amazon', dominio: 'amazon.com.mx', categoria: 'online' },
  { patron: 'MERCADO LIBRE', nombre: 'Mercado Libre', dominio: 'mercadolibre.com.mx', categoria: 'online' },
  { patron: 'MERCADOLIBRE', nombre: 'Mercado Libre', dominio: 'mercadolibre.com.mx', categoria: 'online' },
  { patron: 'MERCADO PAGO', nombre: 'Mercado Pago', dominio: 'mercadopago.com.mx', categoria: 'online' },
  { patron: 'MERCADOPAGO', nombre: 'Mercado Pago', dominio: 'mercadopago.com.mx', categoria: 'online' },
  { patron: 'SHEIN', nombre: 'Shein', dominio: 'shein.com.mx', categoria: 'online' },
  { patron: 'TEMU', nombre: 'Temu', dominio: 'temu.com', categoria: 'online' },
  { patron: 'ALIEXPRESS', nombre: 'AliExpress', dominio: 'aliexpress.com', categoria: 'online' },
  { patron: 'LIVERPOOL', nombre: 'Liverpool', dominio: 'liverpool.com.mx', categoria: 'online' },
  { patron: 'PALACIO DE HIERRO', nombre: 'Palacio de Hierro', dominio: 'elpalaciodehierro.com', categoria: 'online' },
  { patron: 'COPPEL', nombre: 'Coppel', dominio: 'coppel.com', categoria: 'online' },
  { patron: 'ELEKTRA', nombre: 'Elektra', dominio: 'elektra.mx', categoria: 'online' },
  { patron: 'SEARS', nombre: 'Sears', dominio: 'sears.com.mx', categoria: 'online' },
  { patron: 'HOME DEPOT', nombre: 'Home Depot', dominio: 'homedepot.com.mx', categoria: 'hogar' },
  { patron: 'IKEA', nombre: 'IKEA', dominio: 'ikea.com', categoria: 'hogar' },
  { patron: 'ZARA', nombre: 'Zara', dominio: 'zara.com', categoria: 'online' },
  { patron: 'H&M', nombre: 'H&M', dominio: 'hm.com', categoria: 'online' },
  { patron: 'NIKE', nombre: 'Nike', dominio: 'nike.com', categoria: 'online' },
  { patron: 'STEAM', nombre: 'Steam', dominio: 'steampowered.com', categoria: 'entretenimiento' },
  { patron: 'CINEPOLIS', nombre: 'Cinépolis', dominio: 'cinepolis.com', categoria: 'entretenimiento' },
  { patron: 'CINEMEX', nombre: 'Cinemex', dominio: 'cinemex.com', categoria: 'entretenimiento' },
  { patron: 'TICKETMASTER', nombre: 'Ticketmaster', dominio: 'ticketmaster.com.mx', categoria: 'entretenimiento' },
  // Créditos y fintech
  { patron: 'KUESKI', nombre: 'Kueski', dominio: 'kueski.com', categoria: 'fijos' },
  { patron: 'APLAZO', nombre: 'Aplazo', dominio: 'aplazo.mx', categoria: 'msi' },
  { patron: 'KLARNA', nombre: 'Klarna', dominio: 'klarna.com', categoria: 'msi' },
  // Colegiaturas
  { generico: true, patron: 'COLEGIATURA', nombre: 'Colegiatura', dominio: '', categoria: 'colegiaturas', servicio: true },
  { generico: true, patron: 'COLEGIO', nombre: 'Colegio', dominio: '', categoria: 'colegiaturas', servicio: true },
  { generico: true, patron: 'UNIVERSIDAD', nombre: 'Universidad', dominio: '', categoria: 'colegiaturas', servicio: true },
  { generico: true, patron: 'ESCUELA', nombre: 'Escuela', dominio: '', categoria: 'colegiaturas', servicio: true },
  // Seguros
  { patron: 'GNP', nombre: 'GNP Seguros', dominio: 'gnp.com.mx', categoria: 'fijos', servicio: true },
  { patron: 'AXA', nombre: 'AXA Seguros', dominio: 'axa.mx', categoria: 'fijos', servicio: true },
  { patron: 'QUALITAS', nombre: 'Quálitas', dominio: 'qualitas.com.mx', categoria: 'fijos', servicio: true },
  { generico: true, patron: 'SEGURO', nombre: 'Seguro', dominio: '', categoria: 'fijos', servicio: true },
];

/** Dominio del logo del banco/institución por nombre normalizado. */
export const BANCOS: Record<string, { nombre: string; dominio: string; color: string }> = {
  nu: { nombre: 'Nu', dominio: 'nu.com.mx', color: '#820AD1' },
  amex: { nombre: 'Amex', dominio: 'americanexpress.com', color: '#006FCF' },
  bbva: { nombre: 'BBVA', dominio: 'bbva.mx', color: '#072146' },
  banorte: { nombre: 'Banorte', dominio: 'banorte.com', color: '#0B1F17' },
  santander: { nombre: 'Santander', dominio: 'santander.com.mx', color: '#0B1F17' },
  hsbc: { nombre: 'HSBC', dominio: 'hsbc.com.mx', color: '#0B1F17' },
  banamex: { nombre: 'Banamex', dominio: 'banamex.com', color: '#003A70' },
  citibanamex: { nombre: 'Banamex', dominio: 'banamex.com', color: '#003A70' },
  scotiabank: { nombre: 'Scotiabank', dominio: 'scotiabank.com.mx', color: '#0B1F17' },
  inbursa: { nombre: 'Inbursa', dominio: 'inbursa.com', color: '#0B1F17' },
  azteca: { nombre: 'Banco Azteca', dominio: 'bancoazteca.com.mx', color: '#0B1F17' },
  coppel: { nombre: 'Coppel', dominio: 'coppel.com', color: '#F5C400' },
  hey: { nombre: 'Hey Banco', dominio: 'heybanco.com', color: '#0B1F17' },
  klar: { nombre: 'Klar', dominio: 'klar.mx', color: '#0B1F17' },
  stori: { nombre: 'Stori', dominio: 'storicard.com', color: '#0B1F17' },
  mercadopago: { nombre: 'Mercado Pago', dominio: 'mercadopago.com.mx', color: '#0B1F17' },
  gbm: { nombre: 'GBM+', dominio: 'gbm.com', color: '#0B1F17' },
  bitso: { nombre: 'Bitso', dominio: 'bitso.com', color: '#16A34A' },
  cetesdirecto: { nombre: 'CetesDirecto', dominio: 'cetesdirecto.com', color: '#0B1F17' },
  kuspit: { nombre: 'Kuspit', dominio: 'kuspit.com', color: '#0B1F17' },
  efectivo: { nombre: 'Efectivo', dominio: '', color: '#16A34A' },
};

export function infoBanco(nombre: string) {
  const k = nombre.toLowerCase().replace(/[^a-z]/g, '');
  return BANCOS[k] ?? Object.values(BANCOS).find((b) => k.includes(b.nombre.toLowerCase().replace(/[^a-z]/g, ''))) ?? { nombre, dominio: '', color: '#0B1F17' };
}
